language: java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_deploy:
- "./gradlew releaseZip"
deploy:
  provider: heroku
  api_key:
    secure: dce7jjtU7hxFkOY87qKFKzbSckiCSPFpgPEmEpmlyOGX5B23Lt1VQNUXBOUz/naC1mKTYS24FFUSld83eAZYHNQP1773YO3jJ1kScT1RhOXIsRCz0h8/1KWmpgTvHVK2Mi1vnH0vAOAwse5KWMYYbuHpCx6mfl6RatWRbBxll+/IYJ6AWjAZS6JtimMe+pBfKcbKhTNmopROwDbeXFeBlyb5mMB4vAsy+8rnK8r2ZkYOO09Ewi6qmz/KpKhIDDc8JE41orreey3CAFobiZWOJ7HGbKlVXHX0sKyg4BL13dNtcQ3egbHZo36E2f4ZrFmlVbCAlLwJYLJbNpGd4nkFqgDoi106h6b02p3S4mvWAQjdJUThDpDDOd7b4cst3IPZA1rC834VvQNy2UZcYyxSrAF9pvqSCTY7bLtMNNDItNDAAGsqMYGynTJVUv3baAoTKxPbx5udj6muCihSBKgy/pBZOcgD18GyLGCnWRCoghLl5qnjeTkKp75sq40VuVFLf7hKh/MbUqwR6LMy05W7hce0J5sB9qmb34HvRwhxGeKi3kx32zoJPpJ5s0OAPlwyxYDt3dsKlUFf/Rmdk7xv2L7mpr7gZVlsjIqAb9qHe4IWTdgMTt0Y/uZ8cKvijZx0bTfkDsoyOUWEVp2Hl1YJpGCsMecHOgOuCQY+7VDgoZg=
  app: bprzybylski-jalgoarena-problem
  on:
    repo: bartpr/JAlgoArena-Problems
